image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/
    - gradle/wrapper

build & test:
  stage: build
  script:
    - ./gradlew --console=plain :app-amigobox:assembleDebug
    - ./gradlew --console=plain assembleDebugUnitTest testDebugUnitTest ktlintCheck lintDebug
  artifacts:
    when: always
    paths:
      - "**/*.apk"
      - "**/build/reports/lint-results-debug.html"
    reports:
      junit:
        - "**/build/test-results/tests/**/TEST-*.xml"
        - "**/build/test-results/**/TEST-*.xml"
