image: jangrewe/gitlab-ci-android

stages:
  - build

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

build & test:
  stage: build
  script:
    - ./gradlew assembleDebug assembleDebugUnitTest
    - ./gradlew --info -Pci -PbuildDir=lint --console=plain testDebug lintDebug jacocoTestReportDebug
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'
  artifacts:
    paths:
      - "*/build/outputs"
      - "*/build/reports"
      - "*/build/test-results/**"
    when: always
    reports:
      junit:
        - "build/test-results/tests/**/TEST-*.xml"
        - "app-amigobox/build/test-results/**/TEST-*.xml"
        - "lib-commons/build/test-results/**/TEST-*.xml"
        - "lib-domain/build/test-results/**/TEST-*.xml"
        - "lib-nfc/build/test-results/**/TEST-*.xml"
