/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: amigo-platform API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package org.ossiaustria.lib.domain.api

import retrofit2.http.POST
import retrofit2.http.Query
import java.util.*

@JvmSuppressWildcards
interface PasswordApi {

    /**
     * UNSTABLE: Begin password reset process for Account
     * The endpoint is owned by kotlincoroutines service owner
     * @param email email (optional)
     * @param userId user_id (optional)
     * @param userName user_name (optional)
     */

    @POST("auth/password/reset")
    suspend fun passwordReset(
        @Query("email") email: String?,
        @Query("user_id") userId: UUID?,
        @Query("user_name") userName: String?
    ): Unit
}
