/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: amigo-platform API
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package org.ossiaustria.lib.domain.api

import okhttp3.RequestBody
import org.ossiaustria.lib.domain.models.Person
import retrofit2.http.Body
import retrofit2.http.GET
import retrofit2.http.Multipart
import retrofit2.http.PATCH
import retrofit2.http.POST
import retrofit2.http.Part

@JvmSuppressWildcards
interface PersonProfileApi {

    /**
     * Get own Person information (=Profile) for primary or given personId
     * The endpoint is owned by kotlincoroutines service owner
     */
    @GET("profile")
    suspend fun myProfile(): Person

    /**
     * Update Profile for primary or given personId
     * The endpoint is owned by kotlincoroutines service owner
     * @param changePerson changePerson (required)
     */
    @PATCH("profile")
    suspend fun updateProfile(@Body changePerson: ChangePersonDto): Person

    /**
     * Upload Profile's avatar for primary or given personId
     * The endpoint is owned by kotlincoroutines service owner
     * @param file file (required)
     */
    @Multipart
    @POST("profile/avatar")
    suspend fun uploadAvatar(
        @Part("file\"; filename=\"file") file: RequestBody,
    ): Person
}

data class ChangePersonDto(
    val name: String? = null,
    val avatarUrl: String? = null
)